### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by w11211224** [7reax/kyber-mod-manager#9]
is:issue is:

After typing and pressed enter "flutter lib/main.dart", the console gave serveral errors: lib/utils/services/frosty_service.dart(9,8): error GFAA2A68C: Error when reading 'lib/utils/services/frosty_troubleshoot_service.dart': 系统找不到指定的文件�? [C:\Users\w1121\kyber-mod-manager\build\windows\flutter\flutter_assemble.vcxproj] lib/logic/event_cubic.dart(21,37): error G75B77105: Member not found: 'ApiService.getEvents'. [C:\Users\w1121\kyber-mod-manager\build\windows\flutter\flutter_assemble.vcxproj] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: ��C:\Users\w1121\kyber-mod-manager\build\windows\CMakeFiles\ae0e1832156f5c34ea2c34e718bda6cd\flutter_windows.dll.rule;C:\Users\w1121\kyber-mod-manager\build\windows\CMakeFiles\f4f98c633ff8367e1770e99c6a9f0e4e\flutter_assemble.rule�����Զ����������˳�������Ϊ 1�� [C:\Users\w1121\kyber-mod-manager\build\windows\flutter\flutter_assemble.vcxproj] Building Windows application... Exception: Build process failed."  It means serveral files are missing, and they are indeed non-existing in the given path in error

**Comment by 7reax** [comment]
The missing methods have now been added and you simply need to pull the latest changes from the repository to fix the issue. To do this, you can run the command git pull in your project's directory to fetch and merge the latest changes from the remote repository.

Once you have pulled the latest changes, you can try running your Flutter project again to see if the issue has been resolved.
